# wrangler.toml
name = 'i0c'
main = "src/platforms/cloudflare.ts"
compatibility_date = "2025-12-14"

[vars]
ROBOTS_POLICY = "allow"
ANALYTICS_ENDPOINT = "https://u.i0c.cc/api/analytics/events"
ANALYTICS_SOURCE_ID = "i0c.cc"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
